---
- name: Create the keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add ScyllaDB GPG key
  command: >
    gpg --homedir /tmp --no-default-keyring
    --keyring /etc/apt/keyrings/scylladb.gpg
    --keyserver hkp://keyserver.ubuntu.com:80
    --recv-keys {{ scylla_gpg_key }}
  args:
    creates: /etc/apt/keyrings/scylladb.gpg

- name: Add ScyllaDB repository
  get_url:
    url: "http://downloads.scylladb.com/deb/debian/scylla-{{ scylla_version }}.list"
    dest: /etc/apt/sources.list.d/scylla.list

- name: Update apt package index
  apt:
    update_cache: true

- name: Install ScyllaDB package
  apt:
    name: scylla
    state: present
