---


- name: Create keyspace, user, and table
  shell: |
    echo "
    cqlsh  {{ ansible_host }} -u {{ scylla_user }} -p {{ scylla_pass }}
    CREATE USER  {{ scylla_app_user }}  WITH PASSWORD  {{ scylla_app_password }} SUPERUSER;
    GRANT ALL PERMISSIONS ON ALL KEYSPACES TO {{ scylla_app_user }};
    CREATE KEYSPACE IF NOT EXISTS employee_DB WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
    USE employee_DB;
    CREATE TABLE IF NOT EXISTS employee_salary (
      id text,
      process_date text,
      name text,
      salary float,
      status text,
      PRIMARY KEY (id, process_date)
    ) WITH CLUSTERING ORDER BY (process_date DESC);"
